runtime: nodejs20
service: frontend

handlers:
  - url: /static
    static_dir: build/static
  - url: /(.*\..*)
    static_files: build/\
    upload: build/(.*\..*)
  - url: /.*
    static_files: build/index.html
    upload: build/index.html
