runtime: nodejs20
service: default

env_variables:
  NODE_ENV: production
  PORT: 8080
  INSTANCE_CONNECTION_NAME: incident-sim-1755610221:us-central1:incident-response-db
  DB_USER: app_user
  DB_PASSWORD: AppUserPass123!
  DB_NAME: incident_response_db

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

handlers:
  - url: /.*
    script: auto
    secure: always

beta_settings:
  cloud_sql_instances: incident-sim-1755610221:us-central1:incident-response-db
